src/MyBlog.Web.Mvc/ViewComponents/LastAuthorsWidgetViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Core.Services.Interfaces;

namespace MyBlog.Web.Mvc.ViewComponents
{
    public class LastAuthorsWidgetViewComponent(IAuthorService authorService) : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await authorService.GetLastAuthorsWithPostsAsync());
        }
    }
}

src/MyBlog.Web.Mvc/ViewComponents/MostViewedPostsWidgetViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Core.Services.Interfaces;

namespace MyBlog.Web.Mvc.ViewComponents
{
    public class MostViewedPostsWidgetViewComponent(IPostService postService) : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await postService.GetMostViewedPostsAsync());
        }
    }
}

src/MyBlog.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>MyBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyBlog.Web.Mvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
</head>

<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">MyBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a></li>
                    <partial name="_LoginPartial" />
                </ul>                
            </div>
        </div>
    </nav>

    <!-- Page header with logo and tagline-->
    <header class="py-5 bg-light border-bottom mb-4">
        <div class="container">
            <div class="text-center my-5">
                <h1 class="fw-bolder">Bem-vindo ao MyBlog</h1>
            </div>
        </div>
    </header>

    <!-- Page content-->
    <div class="container">
        <div class="row">
            <!-- Blog entries-->
            <div class="col-lg-8">
                @RenderBody()                
            </div>

            @await Html.PartialAsync("_Sidebar")
        </div>
    </div>

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; MyBlog 2024</p></div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery.timeago/jquery.timeago.js"></script>
    <script src="~/lib/jquery.timeago/jquery.timeago.pt-br.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/MyBlog.Web.Mvc/Views/Shared/_Sidebar.cshtml
<!-- Side widgets-->
<div class="col-lg-4">

    @await Html.PartialAsync("_WidgetAdminPanel")

    <!-- Search widget-->
    <div class="card mb-4">
        <div class="card-header">Procurar</div>
        <div class="card-body">
            <form asp-action="Search" asp-controller="Posts" method="get">
            <div class="input-group">                
                    <input class="form-control" type="text" placeholder="Procurar por..." aria-label="Procurar por..." id="term" name="term" aria-describedby="button-search" pattern=".{3,}" title="Informe ao menos três caracteres" required />
                    <button type="submit" class="btn btn-primary" id="button-search"><span class="fa fa-search" /></button>                
            </div>
            </form>
        </div>
    </div>

    <cache expires-after="@TimeSpan.FromMinutes(1)">
        @await Component.InvokeAsync("MostViewedPostsWidget")
    </cache>

    <cache expires-after="@TimeSpan.FromMinutes(1)">
        @await Component.InvokeAsync("LastAuthorsWidget")
    </cache>

    @await Html.PartialAsync("_WidgetNotLoggedUser") 
</div>

src/MyBlog.Web.Mvc/Views/Shared/_WidgetAdminPanel.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager



@if (SignInManager.IsSignedIn(User))
{
    <div class="card mb-4">
        <div class="card-header">Painel administrativo (@User.Identity?.Name)</div> 
        <div class="card-body">
            <p class="card-text"><a asp-action="Create" asp-controller="Posts">Novo post</a> </p>
        </div>
    </div>
}

src/MyBlog.Web.Mvc/Views/Shared/_WidgetNotLoggedUser.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager



@if (!SignInManager.IsSignedIn(User))
{
    <div class="card mb-4">
        <div class="card-header">Painel administrativo</div>
        <div class="card-body">
            <p class="card-text">Para adicionar um novo post, por favor <a asp-area="Identity" asp-page="/Account/Login">autentique-se</a> ou <a asp-area="Identity" asp-page="/Account/Register">registre-se</a> </p>
        </div>
    </div>
}